web:
  build: web
  ports:
    - "80:3000"
  restart: always
  links:
    - rethinkdb
collectors:
  build: collectors
  restart: always
  links:
    - rethinkdb
rethinkdb:
  image: rethinkdb
  restart: always
